name: Build Windows
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: |
         sudo apt install -y eatmydata gcc-mingw-w64
    - id: FETCH_DEPS
      run: cd 3rdparty; ./fetch_and_build.sh x86_64-w64-mingw32
    - id: CONFIGURE
      run: eatmydata ./configure --host=x86_64-w64-mingw32 --with-libxml2=3rdparty/libxml2-winapi --with-zlib=3rdparty/zlib-1.3-winapi
    - id: MAKE
      run: eatmydata make
