name: Build Windows
on:
  push:
    branches:
      - DevelopWindowsVersion

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - run: gcc --version
    - run: cd 3rdparty ; ./fetch_and_build.sh
    - run: ./configure --with-libxml2=3rdparty/libxml2_package
    - run: make
    - run: make test
