name: Build Windows
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - run: gcc --version
    - run: ./configure
    - run: make
    - run: make test
